sudo: false
language: node_js
cache:
  - npm
  - yarn
notifications:
  email: true
node_js:
  - '8'
install:
  - yarn --frozen-lockfile
script:
  - yarn ban -- -f
  - ./next-update-travis.sh
  - yarn lint
  - yarn test
after_success:
  - DEBUG=simple yarn semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
